<?php

namespace Proxies\__CG__\Corporativo\ConcurseiroBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Horario extends \Corporativo\ConcurseiroBundle\Entity\Horario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'coHorario', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'hrInicio', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'hrFim', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'coAtividade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'coDiaSemana'];
        }

        return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'coHorario', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'hrInicio', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'hrFim', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'coAtividade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Horario' . "\0" . 'coDiaSemana'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Horario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoHorario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoHorario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoHorario', []);

        return parent::getCoHorario();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrInicio($hrInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrInicio', [$hrInicio]);

        return parent::setHrInicio($hrInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrInicio', []);

        return parent::getHrInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrFim($hrFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrFim', [$hrFim]);

        return parent::setHrFim($hrFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrFim', []);

        return parent::getHrFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoAtividade(\Corporativo\ConcurseiroBundle\Entity\Atividade $coAtividade = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoAtividade', [$coAtividade]);

        return parent::setCoAtividade($coAtividade);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoAtividade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoAtividade', []);

        return parent::getCoAtividade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoDiaSemana(\Corporativo\ConcurseiroBundle\Entity\DiaSemana $coDiaSemana = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoDiaSemana', [$coDiaSemana]);

        return parent::setCoDiaSemana($coDiaSemana);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoDiaSemana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoDiaSemana', []);

        return parent::getCoDiaSemana();
    }

}
