<?php

namespace Proxies\__CG__\Corporativo\ConcurseiroBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Aluno extends \Corporativo\ConcurseiroBundle\Entity\Aluno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'coAluno', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'nuCpf', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'noEmail', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'tsCadastro', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'isUtilizado', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'coInstituicaoEnsinoPromocao'];
        }

        return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'coAluno', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'nuCpf', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'noEmail', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'tsCadastro', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'isUtilizado', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Aluno' . "\0" . 'coInstituicaoEnsinoPromocao'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Aluno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoAluno()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoAluno();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoAluno', []);

        return parent::getCoAluno();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuCpf($nuCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuCpf', [$nuCpf]);

        return parent::setNuCpf($nuCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuCpf', []);

        return parent::getNuCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoEmail($noEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoEmail', [$noEmail]);

        return parent::setNoEmail($noEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoEmail', []);

        return parent::getNoEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTsCadastro($tsCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTsCadastro', [$tsCadastro]);

        return parent::setTsCadastro($tsCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getTsCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTsCadastro', []);

        return parent::getTsCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUtilizado($isUtilizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUtilizado', [$isUtilizado]);

        return parent::setIsUtilizado($isUtilizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUtilizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUtilizado', []);

        return parent::getIsUtilizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoInstituicaoEnsinoPromocao(\Corporativo\ConcurseiroBundle\Entity\InstituicaoEnsinoPromocao $coInstituicaoEnsinoPromocao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoInstituicaoEnsinoPromocao', [$coInstituicaoEnsinoPromocao]);

        return parent::setCoInstituicaoEnsinoPromocao($coInstituicaoEnsinoPromocao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoInstituicaoEnsinoPromocao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoInstituicaoEnsinoPromocao', []);

        return parent::getCoInstituicaoEnsinoPromocao();
    }

}
