<?php

namespace Proxies\__CG__\Corporativo\ConcurseiroBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReferenciaValor extends \Corporativo\ConcurseiroBundle\Entity\ReferenciaValor implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'coReferenciaValor', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'vlValor', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'dtInicioValidade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'dtFimValidade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'isAtivo'];
        }

        return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'coReferenciaValor', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'vlValor', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'dtInicioValidade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'dtFimValidade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\ReferenciaValor' . "\0" . 'isAtivo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ReferenciaValor $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoReferenciaValor()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoReferenciaValor();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoReferenciaValor', []);

        return parent::getCoReferenciaValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlValor($vlValor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlValor', [$vlValor]);

        return parent::setVlValor($vlValor);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlValor', []);

        return parent::getVlValor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtInicioValidade($dtInicioValidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtInicioValidade', [$dtInicioValidade]);

        return parent::setDtInicioValidade($dtInicioValidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtInicioValidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtInicioValidade', []);

        return parent::getDtInicioValidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtFimValidade($dtFimValidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtFimValidade', [$dtFimValidade]);

        return parent::setDtFimValidade($dtFimValidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtFimValidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtFimValidade', []);

        return parent::getDtFimValidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsAtivo($isAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsAtivo', [$isAtivo]);

        return parent::setIsAtivo($isAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsAtivo', []);

        return parent::getIsAtivo();
    }

}
