<?php

namespace Proxies\__CG__\Corporativo\ConcurseiroBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CargoDisciplina extends \Corporativo\ConcurseiroBundle\Entity\CargoDisciplina implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'coCargoDisciplina', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'nuPeso', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'nuQtdQuestao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'coCargo', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'coDisciplina'];
        }

        return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'coCargoDisciplina', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'nuPeso', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'nuQtdQuestao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'coCargo', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\CargoDisciplina' . "\0" . 'coDisciplina'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CargoDisciplina $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoCargoDisciplina()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoCargoDisciplina();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoCargoDisciplina', []);

        return parent::getCoCargoDisciplina();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuPeso($nuPeso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuPeso', [$nuPeso]);

        return parent::setNuPeso($nuPeso);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuPeso', []);

        return parent::getNuPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuQtdQuestao($nuQtdQuestao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuQtdQuestao', [$nuQtdQuestao]);

        return parent::setNuQtdQuestao($nuQtdQuestao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuQtdQuestao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuQtdQuestao', []);

        return parent::getNuQtdQuestao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoCargo(\Corporativo\ConcurseiroBundle\Entity\Cargo $coCargo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoCargo', [$coCargo]);

        return parent::setCoCargo($coCargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoCargo', []);

        return parent::getCoCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoDisciplina(\Corporativo\ConcurseiroBundle\Entity\Disciplina $coDisciplina = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoDisciplina', [$coDisciplina]);

        return parent::setCoDisciplina($coDisciplina);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoDisciplina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoDisciplina', []);

        return parent::getCoDisciplina();
    }

}
