<?php

namespace Proxies\__CG__\Corporativo\ConcurseiroBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EstudoAssunto extends \Corporativo\ConcurseiroBundle\Entity\EstudoAssunto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coEstudoAssunto', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coAssunto', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coDiaHorarioEstudo', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coTipoEstudo'];
        }

        return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coEstudoAssunto', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coAssunto', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coDiaHorarioEstudo', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\EstudoAssunto' . "\0" . 'coTipoEstudo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EstudoAssunto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoEstudoAssunto()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoEstudoAssunto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoEstudoAssunto', []);

        return parent::getCoEstudoAssunto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoAssunto(\Corporativo\ConcurseiroBundle\Entity\Assunto $coAssunto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoAssunto', [$coAssunto]);

        return parent::setCoAssunto($coAssunto);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoAssunto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoAssunto', []);

        return parent::getCoAssunto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoDiaHorarioEstudo(\Corporativo\ConcurseiroBundle\Entity\DiaHorarioEstudo $coDiaHorarioEstudo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoDiaHorarioEstudo', [$coDiaHorarioEstudo]);

        return parent::setCoDiaHorarioEstudo($coDiaHorarioEstudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoDiaHorarioEstudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoDiaHorarioEstudo', []);

        return parent::getCoDiaHorarioEstudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoTipoEstudo(\Corporativo\ConcurseiroBundle\Entity\TipoEstudo $coTipoEstudo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoTipoEstudo', [$coTipoEstudo]);

        return parent::setCoTipoEstudo($coTipoEstudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoTipoEstudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoTipoEstudo', []);

        return parent::getCoTipoEstudo();
    }

}
