<?php

namespace Proxies\__CG__\Corporativo\ConcurseiroBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Atividade extends \Corporativo\ConcurseiroBundle\Entity\Atividade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'coAtividade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'noNome', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'deDescricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'noCor', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'hrMinimoRegra', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'hrMaximoRegra', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'isParaleloRegra'];
        }

        return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'coAtividade', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'noNome', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'deDescricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'noCor', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'hrMinimoRegra', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'hrMaximoRegra', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Atividade' . "\0" . 'isParaleloRegra'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Atividade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoAtividade()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoAtividade();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoAtividade', []);

        return parent::getCoAtividade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoNome($noNome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoNome', [$noNome]);

        return parent::setNoNome($noNome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoNome', []);

        return parent::getNoNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeDescricao($deDescricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeDescricao', [$deDescricao]);

        return parent::setDeDescricao($deDescricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeDescricao', []);

        return parent::getDeDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCor($noCor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCor', [$noCor]);

        return parent::setNoCor($noCor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCor', []);

        return parent::getNoCor();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrMinimoRegra($hrMinimoRegra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrMinimoRegra', [$hrMinimoRegra]);

        return parent::setHrMinimoRegra($hrMinimoRegra);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrMinimoRegra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrMinimoRegra', []);

        return parent::getHrMinimoRegra();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrMaximoRegra($hrMaximoRegra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrMaximoRegra', [$hrMaximoRegra]);

        return parent::setHrMaximoRegra($hrMaximoRegra);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrMaximoRegra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrMaximoRegra', []);

        return parent::getHrMaximoRegra();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsParaleloRegra($isParaleloRegra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsParaleloRegra', [$isParaleloRegra]);

        return parent::setIsParaleloRegra($isParaleloRegra);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsParaleloRegra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsParaleloRegra', []);

        return parent::getIsParaleloRegra();
    }

}
