<?php

namespace Proxies\__CG__\Corporativo\ConcurseiroBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Concurso extends \Corporativo\ConcurseiroBundle\Entity\Concurso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'coConcurso', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'noNome', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'deDescricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'noLinkEdital', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'dtAberturaInscricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'dtFinalInscricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'dtProva', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'isAtivo', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'coBanca', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'coReferenciaValor'];
        }

        return ['__isInitialized__', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'coConcurso', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'noNome', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'deDescricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'noLinkEdital', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'dtAberturaInscricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'dtFinalInscricao', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'dtProva', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'isAtivo', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'coBanca', '' . "\0" . 'Corporativo\\ConcurseiroBundle\\Entity\\Concurso' . "\0" . 'coReferenciaValor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Concurso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoConcurso()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoConcurso();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoConcurso', []);

        return parent::getCoConcurso();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoNome($noNome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoNome', [$noNome]);

        return parent::setNoNome($noNome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoNome', []);

        return parent::getNoNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeDescricao($deDescricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeDescricao', [$deDescricao]);

        return parent::setDeDescricao($deDescricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeDescricao', []);

        return parent::getDeDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoLinkEdital($noLinkEdital)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoLinkEdital', [$noLinkEdital]);

        return parent::setNoLinkEdital($noLinkEdital);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoLinkEdital()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoLinkEdital', []);

        return parent::getNoLinkEdital();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtAberturaInscricao($dtAberturaInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtAberturaInscricao', [$dtAberturaInscricao]);

        return parent::setDtAberturaInscricao($dtAberturaInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtAberturaInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtAberturaInscricao', []);

        return parent::getDtAberturaInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtFinalInscricao($dtFinalInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtFinalInscricao', [$dtFinalInscricao]);

        return parent::setDtFinalInscricao($dtFinalInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtFinalInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtFinalInscricao', []);

        return parent::getDtFinalInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtProva($dtProva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtProva', [$dtProva]);

        return parent::setDtProva($dtProva);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtProva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtProva', []);

        return parent::getDtProva();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsAtivo($isAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsAtivo', [$isAtivo]);

        return parent::setIsAtivo($isAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsAtivo', []);

        return parent::getIsAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoBanca(\Corporativo\ConcurseiroBundle\Entity\Banca $coBanca = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoBanca', [$coBanca]);

        return parent::setCoBanca($coBanca);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoBanca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoBanca', []);

        return parent::getCoBanca();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoReferenciaValor(\Corporativo\ConcurseiroBundle\Entity\ReferenciaValor $coReferenciaValor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoReferenciaValor', [$coReferenciaValor]);

        return parent::setCoReferenciaValor($coReferenciaValor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoReferenciaValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoReferenciaValor', []);

        return parent::getCoReferenciaValor();
    }

}
